version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: infoplus-mysql
    environment:
      MYSQL_DATABASE: info_plus
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - infoplus-network

  app:
    build: .
    container_name: infoplus-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/info_plus?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8080:8080"
    networks:
      - infoplus-network

networks:
  infoplus-network:

volumes:
  mysql-data: